//
//  FlowerShare.swift
//  FlowerPowerGame
//
//  One flower, packaged up to send to somebody else.
//
//  The transport is a file. Not a server, not an account, not a friends list:
//  a small self-contained document that goes through the share sheet, so it
//  works in Messages, Mail, AirDrop, or anything else the recipient has. That
//  keeps the game offline-first — which it already is, since the engine is
//  deterministic and the save is a local file — and it means sharing a flower
//  costs nobody a backend.
//
//  Two things here are not conveniences, and both concern the fact that this
//  data crosses between people.
//
//  Location is off by default
//  --------------------------
//  A flower photograph's coordinate is where a person was standing. Often
//  that is their garden, which is to say their home address. The game reads
//  EXIF location to place patches on the map and to work out how far the bees
//  fly, so the coordinate is right there and it would be easy to include it.
//  It is not included unless the sender asks for it, and even then the default
//  is rounded to about a kilometre. Sending a flower to a group chat should
//  never be a way to tell everyone in it where you live.
//
//  The image is re-encoded rather than forwarded, which drops the original
//  EXIF wholesale — including the location, the timestamp, and the device.
//
//  Everything received is untrusted
//  --------------------------------
//  A `.flower` file arrives from outside the app and nothing about it is
//  guaranteed. It may be truncated, hand-edited, or built to be hostile: a
//  hundred-megabyte image, a confidence of 10^9, a species identifier that is
//  not a species. `validated()` is what every import goes through, and it
//  clamps rather than trusts.
//

import Foundation
import FlowerPowerCore

public struct FlowerShare: Codable, Equatable, Sendable, Identifiable {

    /// Bumped when the shape changes incompatibly. A file from the future is
    /// refused with something a person can read rather than a decode error.
    public static let currentVersion = 1

    /// The largest image this will carry, before base64. Comfortably more than
    /// a downscaled photograph needs and far less than a decompression bomb.
    public static let maximumImageBytes = 4 * 1024 * 1024

    /// Filename extension and uniform type identifier. Must match the document
    /// type declared in `project.yml`.
    public static let fileExtension = "flower"
    public static let contentType = "com.kylepeterson.flowerpower.flower"

    /// A gift, or a request for one.
    public enum Kind: String, Codable, Sendable {
        case gift
        case request
    }

    public var version: Int
    /// Identifies this share, so importing it twice does nothing. Generated by
    /// the sender; two people sharing the same photograph produce two shares,
    /// which is correct — they are two separate gifts.
    public var id: String
    /// Optional for compatibility: a file from before requests existed is a
    /// gift, which is all there was.
    public var kind: Kind?
    /// For a request: the families the sender's bees are short of.
    public var wanted: [PlantFamily]?
    /// For a request: the sender's colony's season, so the recipient sees
    /// what would help now.
    public var season: Season?
    /// Catalogue identifier, resolved against the *recipient's* catalogue.
    /// `nil`, or a name they do not have, simply means unidentified.
    public var speciesID: String?
    public var confidence: Double
    public var takenAt: Date
    /// Whatever the sender chose to be called. Never filled in automatically
    /// from the device name.
    public var sharedBy: String?
    /// A line from the sender, shown on import.
    public var note: String?
    /// Present only when the sender opted in. See the note at the top.
    public var latitude: Double?
    public var longitude: Double?
    /// JPEG bytes.
    public var imageData: Data

    public init(
        version: Int = FlowerShare.currentVersion,
        id: String = UUID().uuidString,
        speciesID: String?,
        confidence: Double,
        takenAt: Date,
        sharedBy: String?,
        note: String? = nil,
        latitude: Double? = nil,
        longitude: Double? = nil,
        imageData: Data
    ) {
        self.version = version
        self.id = id
        self.speciesID = speciesID
        self.confidence = confidence
        self.takenAt = takenAt
        self.sharedBy = sharedBy
        self.note = note
        self.latitude = latitude
        self.longitude = longitude
        self.imageData = imageData
    }

    public var coordinate: GeoPoint? {
        guard let latitude, let longitude else { return nil }
        return GeoPoint(latitude: latitude, longitude: longitude)
    }

    public var isRequest: Bool { kind == .request }

    /// A request for forage: no photograph, a list of families.
    public static func request(
        wanted: [PlantFamily],
        season: Season,
        sharedBy: String?,
        note: String? = nil
    ) -> FlowerShare {
        var share = FlowerShare(
            speciesID: nil, confidence: 0, takenAt: Date(),
            sharedBy: sharedBy, note: note, imageData: Data()
        )
        share.kind = .request
        share.wanted = wanted
        share.season = season
        return share
    }

    /// One line for the recipient of a request.
    public var requestSummary: String {
        let families = (wanted ?? []).map { $0.commonName.lowercased() }
        let who = sharedBy ?? "A friend"
        guard !families.isEmpty else {
            return "\(who)'s bees are short of forage."
        }
        return "\(who)'s bees are short of \(families.spokenList)."
    }

    /// How the local photo store and the garden refer to a received image.
    /// The recipient has no photo library asset for it — it never entered
    /// their library, deliberately — so it is keyed by share id instead.
    public var localIdentifier: String { Self.localIdentifier(forShare: id) }

    public static func localIdentifier(forShare id: String) -> String {
        "shared:\(id)"
    }

    /// Whether an identifier refers to a received flower rather than a photo
    /// in the player's own library.
    public static func isSharedIdentifier(_ identifier: String) -> Bool {
        identifier.hasPrefix("shared:")
    }
}

// MARK: - How precisely to say where it was

public enum LocationSharing: String, CaseIterable, Sendable, Identifiable {

    /// Send no location at all. The recipient's bees fly a nominal distance
    /// and the flower does not appear on their map.
    case none
    /// Rounded to roughly a kilometre — enough to say which part of town,
    /// not enough to say which house.
    case approximate
    /// Exactly where the photograph was taken.
    case exact

    public var id: String { rawValue }

    public var title: String {
        switch self {
        case .none: return "Don't Share Location"
        case .approximate: return "Approximate Area"
        case .exact: return "Exact Spot"
        }
    }

    public var detail: String {
        switch self {
        case .none:
            return "The flower still feeds their bees, at a guessed distance."
        case .approximate:
            return "Rounded to about a kilometre. Enough to find the meadow, not your door."
        case .exact:
            return "Where you were standing. Only for places you would tell anyone about."
        }
    }

    /// Degrees to round to. 0.01 degrees of latitude is about 1.1 km, and of
    /// longitude rather less depending on how far north you are — which is
    /// fine, because the point is deliberate imprecision.
    private static let approximateGrid = 0.01

    public func apply(to coordinate: GeoPoint?) -> GeoPoint? {
        guard let coordinate else { return nil }

        switch self {
        case .none:
            return nil
        case .exact:
            return coordinate
        case .approximate:
            return GeoPoint(
                latitude: (coordinate.latitude / Self.approximateGrid).rounded()
                    * Self.approximateGrid,
                longitude: (coordinate.longitude / Self.approximateGrid).rounded()
                    * Self.approximateGrid
            )
        }
    }
}

// MARK: - Reading and writing

public enum FlowerShareError: Error, LocalizedError, Equatable {
    case notAFlowerFile
    case fromANewerVersion(Int)
    case imageTooLarge(Int)
    case noImage

    public var errorDescription: String? {
        switch self {
        case .notAFlowerFile:
            return "That does not look like a flower someone sent."
        case .fromANewerVersion:
            return "This flower came from a newer version of FlowerPower. Update to open it."
        case .imageTooLarge:
            return "That flower's photograph is too large to open."
        case .noImage:
            return "That flower arrived without a photograph."
        }
    }
}

extension FlowerShare {

    private static func encoder() -> JSONEncoder {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        return encoder
    }

    private static func decoder() -> JSONDecoder {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return decoder
    }

    public func encoded() throws -> Data {
        try Self.encoder().encode(self)
    }

    /// Reads a share and makes it safe to act on.
    ///
    /// Everything about the input is suspect: it came from another device, by
    /// way of a messaging app, and may have been edited on the way. Nothing
    /// here trusts a value it can clamp instead.
    public static func decoded(from data: Data) throws -> FlowerShare {
        guard data.count <= maximumImageBytes * 2 else {
            throw FlowerShareError.imageTooLarge(data.count)
        }

        let share: FlowerShare
        do {
            share = try decoder().decode(FlowerShare.self, from: data)
        } catch {
            throw FlowerShareError.notAFlowerFile
        }

        guard share.version <= currentVersion else {
            throw FlowerShareError.fromANewerVersion(share.version)
        }
        // A request carries no photograph, by design.
        guard share.isRequest || !share.imageData.isEmpty else {
            throw FlowerShareError.noImage
        }
        guard share.imageData.count <= maximumImageBytes else {
            throw FlowerShareError.imageTooLarge(share.imageData.count)
        }

        return share.validated()
    }

    /// Brings every field into a range the game can act on.
    ///
    /// Deliberately clamps rather than rejecting. A share with a silly
    /// confidence is far more likely to be a bug or an old version than an
    /// attack, and throwing away somebody's flower over it would be the wrong
    /// trade — but acting on 10^9 confidence would hand the recipient a patch
    /// worth more than the rest of their garden put together.
    public func validated() -> FlowerShare {
        var copy = self

        copy.confidence = confidence.isFinite ? min(1, max(0, confidence)) : 0

        // An identifier the recipient's catalogue does not have becomes no
        // identifier. Their bees work an unnamed flower perfectly well.
        if let speciesID, FlowerCatalogue.species(withID: speciesID) == nil {
            copy.speciesID = nil
        }

        copy.sharedBy = sharedBy.map(Self.trimmedForDisplay).flatMap { $0.isEmpty ? nil : $0 }
        copy.note = note.map(Self.trimmedForDisplay).flatMap { $0.isEmpty ? nil : $0 }

        // A coordinate off the globe is meaningless, and a distance computed
        // from one would be too.
        if let latitude, let longitude,
           latitude.isFinite, longitude.isFinite,
           (-90...90).contains(latitude), (-180...180).contains(longitude) {
            copy.latitude = latitude
            copy.longitude = longitude
        } else {
            copy.latitude = nil
            copy.longitude = nil
        }

        // A share that arrives claiming to be from the future would make a
        // patch that is somehow not yet discovered.
        if takenAt > Date().addingTimeInterval(60 * 60 * 24) {
            copy.takenAt = Date()
        }

        if id.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            copy.id = UUID().uuidString
        }

        // A request's family list is capped and deduplicated. A gift carries
        // none.
        if copy.isRequest {
            var seen = Set<PlantFamily>()
            copy.wanted = (wanted ?? []).filter { seen.insert($0).inserted }.prefix(8).map { $0 }
            copy.imageData = Data()
            copy.latitude = nil
            copy.longitude = nil
        } else {
            copy.wanted = nil
            copy.season = nil
        }

        return copy
    }

    /// Text from another person, on its way to a label. Length-capped and
    /// stripped of newlines so it cannot break the layout it lands in.
    private static func trimmedForDisplay(_ text: String) -> String {
        text
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .prefix(80)
            .description
    }

    public var species: FlowerSpecies? {
        speciesID.flatMap(FlowerCatalogue.species(withID:))
    }

    /// What to call it in the interface before it is imported.
    public var displayName: String {
        species?.commonName ?? "An unidentified flower"
    }
}
